name: Deploy Docs

on:
  # 文档推送时执行
  push:
    branches: [nga]
    paths:
      - "docs/**"
      - ".github/**"
  # 文档 PR 时执行
  pull_request:
    branches: [nga]
    paths:
      - "docs/**"
      - ".github/**"
  # 可手动执行
  workflow_dispatch:

# 确保同时只有一个部署在运行
concurrency:
  group: docs-deployer
  cancel-in-progress: true

jobs:
  # 任务: 部署 Pages
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      # 1、检出源码
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # 默认只拉取分支最近一次的 commit，可能会导致一些文章的 GitInfo 变量无法获取，设为 0 代表拉取所有分支所有提交
          fetch-depth: 0
          submodules: recursive
      # 2、配置 Git
      # 主要是 quotePath，默认情况下，文件名包含中文时，git 会使用引号把文件名括起来，这会导致 action 中无法读取 :GitInfo 变量
      - name: Git Config
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false
      # 3、安装 PNPM
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
      # 4、安装 Node 环境
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
          cache: pnpm
          cache-dependency-path: docs
      # 5、安装依赖
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
        working-directory: docs
      # 6、打包
      - name: Build
        run: pnpm build
        working-directory: docs
      # 7、部署 Pages
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs-dist
          folder: docs/dist
          clean: true
          single-commit: true
